mobtimeapp/mobtime

ngrok.js
package.json
src/actions.js
src/checkVersion.js
src/http.js
src/index.js
yarn.lock

Separated ngrok again, since it wasn't cleaning up properly
Closes #10

Check version effect

---

public/index.html
src/http.js

Add statistics

---

public/actions.js
src/api/goals.js
src/api/mob.js
src/api/timer.js
src/http.js

Modularize http api endpoints for server

---

src/index.js

- Prevent notification broadcast if timer is reset but timer doesn't have a start time
- Closes #46

Don't send notification if timer is already reset

---

public/actions.js
public/components/mobber.js
public/components/reorderable.js
public/dragAndDrop.js
public/index.js
src/actions.js
src/api/mob.js
src/index.js

9 drag to reorder

---

.gitignore
README.md
deploy/initiate.sh.example
deploy/work.sh.example
package.json

Deploy with passenger

---

public/subscriptions.js
src/http.js

Allow websocket to create timer

---

database/migrations/20200425154552_CreateBlacklistTable.js
package.json
src/auditLog.js
src/blacklist.js
src/database.js
src/http.js
src/index.js
src/tokenPolice.js

62 prevent bots from flooding timers

---

public/actions.js
public/effects.js
public/subscriptions.js
public/timer.js
src/persistence.js

74 reconnect after deploy

---

public/actions.js

- Closes #59 
- Mobbing with @dansoppelsa, @NDavisDevelopment, and @nickdown

Zero out timer on end

---

public/actions.js
public/components/badge.js
public/components/goal.js
public/components/mobber.js
public/components/overviewHeading.js
public/components/tab.js
public/sections/goalList.js
public/sections/mobParticipants.js
public/timer.js

- Add overview tab
- Show limited mob and goals in overview
- Make tab layout more flex-y
- Closes #83 
- @dansoppelsa
- @jrepta
- @nickdown
- @alisondraV

83 overview tab

---

package.json
src/index.js
src/lib/migrations.js
src/lib/migrations.test.js
src/load.js
src/migrations/0000_initialSchema.js
src/timerConfig.js
yarn.lock

- Remove unused dependency on concurrently
- Add ava for testing backend code
- Create migrations folder in src for in-memory timer migrations on boot
- 
- Closes #84

84 timer data migration

---

public/actions.js
public/components/mobber.js
public/sections/mobParticipants.js
src/api/mob.js
src/id.js
src/index.js
src/migrations/0001_mob_id.js

- Use object to describe mobber
- Update mob remove endpoint to accept an id
- Add model migration to ensure that all mobbers are `{ name, id }` structured
- Closes #50

Use mobber id to remove a mobber

---

public/settings/setLength.js

Fix turn duration input

---

package.json
public/actions.js
public/actions.move-collection.test.js
public/effects.js

- Extract drag and drop
- Add test around actions
- Expose and fix mob and goal move actions

Fix drag and drop bug

---

public/actions.goal.test.js
public/actions.js
public/sections/addGoal.js

Hi, 
This pull request makes it so submitting a semicolon-seperated string into the "Add Goal" box makes the goal get added as multiple goals.  It basically just modifies the "actuions.AddGoal" function.
Closes #125 
My apologies for any bad code here; I'm quite new to javascript and not sure about best practices.  
Any feedback is most welcome, and I hope you'll consider this feature for merging!
Best wishes,
Nick

Multiple goals can be added at once, if seperated by a semicolon

---

public/components/checkbox.js

Make checkmarks clickable

---

.eslintrc.js
.gitignore
package.json
public/actions.js
public/actions.misc.test.js
public/actions.notifications.test.js
public/effects.js
public/effects.test.js
public/index.html
public/timer.html
public/timer.js
yarn.lock

Notification bug

---

.gitignore
public/actions.goal.test.js
public/actions.js
public/sections/removeCompletedGoals.js
public/timer.js

This PR was collaboratively developed with @dbartholomae @haraldreingruber @dpolivaev @jagandeep @christianhujer & @mrozbarry during a "Mob Programming on Open Source Software" meetup!

Add a button  to clear completed goals

---

public/e2e.test.js

Prove that there is no bug present while removing next driver with 12 mobbers

---

README.md

I ran the instructions in the README, but was confused since the styling was missing. I ran Tailwind and it fixed it, so its probably worth mentioning this in the setup steps.

Add Tailwind step to initial setup instructions

---

public/sections/addGoal.js
public/sections/addParticipant.js
public/sections/removeCompletedGoals.js

Remove autocomplete from forms

---

Dockerfile
README.md
docker-compose.yml
src/index.js

This PR adds support for Docker containerisation for the app.

Containerised the application

---

deploy/index.js
package.json

- Also add better error when deploy fails without a TARGET env set

Remove husky from postinstall

---

public/actions.js
public/actions.mob.test.js

Spread effects in CycleMob action

---

deploy/work.sh.example
package-lock.json
package.json
tailwind.config.js

Fix deploys

---

docker/app/Dockerfile
package.json
public/components/mobber.js
public/sections/mobActions.js

Highlight mob positions

---

public/actions.goal.test.js
public/actions.js
public/actions.mob-rename.test.js
public/actions.mob.test.js
public/actions.move-collection.test.js
public/actions.settings.test.js
public/actions.timer.test.js
public/effects.js
public/effects.test.js
public/lib/emitter.js
public/subscriptions.js
public/timer.js
src/actions.js
src/actions.test.js
src/queue.js
src/websocket.js

A little more restructuring to make websocket behave better

---

public/index.html
src/api/statistics.js
src/queue.js

- Connections can duplicate under some circumstances

Show number of mobbers instead of connections

---

Dockerfile
Dockerfile.production
README.md
docker-compose.development.yml
docker-compose.production.yml
docker-compose.yml
package.json

docker-compose settings is wrong and not work now.
I fixed compose and healthcheck like below `healthy`.
```sh
ᐅ docker ps
CONTAINER ID   IMAGE         COMMAND                  CREATED              STATUS                        PORTS                    NAMES
410cdfe981a5   mobtime_app   "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:1234->1234/tcp   mobtime-app
55033d8c9a23   redis         "docker-entrypoint.s…"   27 minutes ago       Up About a minute             6379/tcp                 cache
```

Fix docker-compose

---

public/effects.js
public/tabs/qrShare.js

Effect location parse error

---

package-lock.json
package.json

This constantly causes issues for new PRs/contributors, and it was supposed to save me headaches

Remove eslint/prettier

---

public/i18n/af-ZA.js
public/i18n/index.js

This adds Afrikaans translations for the mobtime app.

Add Afrikaans translations
